spring:
  profiles:
    active: dev
  application:
    name: online-banking
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    username: postgres
    password: anhemoi012
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO
    com:
      windev:
        online_banking: DEBUG
  file:
    name: online-banking.log
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always